export const TODOS = 'GET TODO LIST';
export const ADD_TODO = 'ADD NEW TODO';
export const REMOVE_TODO = 'REMOVE TODO FROM LIST';
export const TOGGLE_TODO = 'CHANGE TODO FROM NOT COMPLETED TO COMPLETED';
export const SET_FILTER = 'FILTERS TODO ACCORDING TO STATE'

